x-test-variables: &test-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: db
  PG_HOST: db_test_postgresql
  PG_PORT: 5432
  APP_PORT: 5000

services:
  db_static_checks:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
      uv run ty check &&
      uv run ruff check &&
      uv run ruff format --check
      "
    environment:
      <<: *test-env

  db_test_postgresql:
    image: postgres:18-trixie
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      <<: *test-env
    networks:
      - db_network
    depends_on:
      db_static_checks:
        condition: service_completed_successfully

  db_tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
      uv run alembic upgrade head &&
      uv run pytest --cov --durations=0
      "
    environment:
      <<: *test-env
    networks:
      - db_network
    depends_on:
      db_static_checks:
        condition: service_completed_successfully
      db_test_postgresql:
        condition: service_healthy

networks:
  db_network:
